2025-08-14 09:13:29,335 - INFO - Lancement du scraping pour Restaurants à Paris
2025-08-14 09:13:48,860 - INFO - Extrait: SAS TABLE NEUF | Tel:     01 83 89 08 78
2025-08-14 09:13:50,994 - INFO - Extrait: Le 59 | Tel: 01 80 50 00 29
2025-08-14 09:13:53,139 - INFO - Fichier sauvegardé : pagesjaunes_Restaurants_Paris_20250814_0913.csv (2 résultats)
2025-08-14 09:14:18,172 - INFO - Lancement du scraping pour Restaurants à Paris
2025-08-14 09:14:35,613 - INFO - Extrait: Gabriela | Tel: 01 42 80 28 14
2025-08-14 09:14:37,732 - INFO - Extrait: Café du Commerce | Tel: 07 72 17 02 88
2025-08-14 09:14:39,864 - INFO - Extrait: Le Moghol | Tel: 01 40 06 90 36
2025-08-14 09:14:41,981 - INFO - Extrait: SAS TABLE NEUF | Tel:     01 83 89 08 78
2025-08-14 09:14:44,095 - INFO - Extrait: Espace Aurore | Tel: 01 53 94 51 00, 01 53 94 51 02
2025-08-14 09:14:46,207 - INFO - Extrait: Santa Carne | Tel: 01 42 72 03 07
2025-08-14 09:14:48,327 - INFO - Extrait: Café le Marivaux | Tel: 01 42 96 40 66, 09 67 41 40 66
2025-08-14 09:14:50,455 - INFO - Extrait: Truffes Folies | Tel: 01 44 18 05 41, 06 03 26 56 24
2025-08-14 09:14:52,576 - INFO - Extrait: Nanwich Riquet | Tel: 01 44 53 91 70, 07 53 82 93 01
2025-08-14 09:14:54,699 - INFO - Extrait: Le Caveau de l'Isle | Tel: 01 43 25 10 26
2025-08-14 09:14:56,825 - INFO - Fichier sauvegardé : pagesjaunes_Restaurants_Paris_20250814_0914.csv (10 résultats)
2025-08-14 09:36:26,018 - INFO - Recherche: Restaurants à Paris
2025-08-14 09:36:37,555 - INFO - 1/2: Eiffel Croisières - Péniche Ivoire
2025-08-14 09:36:48,781 - WARNING - Échec de fermeture standard: Message: 
Stacktrace:
	GetHandleVerifier [0x0xa2fd33+62915]
	GetHandleVerifier [0x0xa2fd74+62980]
	(...
2025-08-14 09:36:48,787 - WARNING - Échec de ESC, tentative de rechargement
2025-08-14 09:37:09,415 - WARNING - Échec de fermeture standard: Message: 
Stacktrace:
	GetHandleVerifier [0x0xa2fd33+62915]
	GetHandleVerifier [0x0xa2fd74+62980]
	(...
2025-08-14 09:37:09,419 - WARNING - Échec de ESC, tentative de rechargement
2025-08-14 09:37:17,825 - INFO - Données sauvegardées dans google_maps_Restaurants_Paris_20250814_093717.xlsx (1 entrées valides)
2025-08-14 09:44:51,497 - INFO - Recherche: Restaurants à Paris
2025-08-14 09:45:04,063 - INFO - 1/2: Eiffel Croisières - Péniche Ivoire
2025-08-14 09:45:14,271 - ERROR - Erreur sur l'élément 1: Message: 
Stacktrace:
	GetHandleVerifier [0x0xa2fd33+62915]
	GetHandleVerifier [0x0xa2fd74+62980]
	(No symbol) [0x0x863e13]
	(No symbol) [0x0x8ac89e]
	(No symbol) [0x0x8acc3b]
	(No symbol) [0x0x8f4ec2]
	(No symbol) [0x0x8d1424]
	(No symbol) [0x0x8f26ea]
	(No symbol) [0x0x8d11d6]
	(No symbol) [0x0x8a0833]
	(No symbol) [0x0x8a16a4]
	GetHandleVerifier [0x0xc98d23+2590131]
	GetHandleVerifier [0x0xc93f6a+2570234]
	GetHandleVerifier [0x0xa559ea+217722]
	GetHandleVerifier [0x0xa46058+153832]
	GetHandleVerifier [0x0xa4c4bd+179533]
	GetHandleVerifier [0x0xa37738+94152]
	GetHandleVerifier [0x0xa378c2+94546]
	GetHandleVerifier [0x0xa22bda+9322]
	BaseThreadInitThunk [0x0x761ffcc9+25]
	RtlGetAppContainerNamedObjectPath [0x0x770882ae+286]
	RtlGetAppContainerNamedObjectPath [0x0x7708827e+238]

2025-08-14 09:45:16,547 - INFO - Données sauvegardées dans google_maps_Restaurants_Paris_20250814_094516.xlsx (1 entrées valides)
2025-08-14 09:46:34,907 - INFO - Recherche: Restaurants à Paris
2025-08-14 09:46:45,715 - INFO - 1/2: Eiffel Croisières - Péniche Ivoire
2025-08-14 09:46:50,877 - WARNING - Liste non réapparue, saut forcé
2025-08-14 09:46:54,036 - INFO - Données sauvegardées dans google_maps_Restaurants_Paris_20250814_094653.xlsx (1 entrées valides)
2025-08-14 09:58:18,780 - INFO - Recherche: Restaurants à Paris
2025-08-14 09:58:28,886 - INFO - 1/2: Eiffel Croisières - Péniche Ivoire
2025-08-14 09:58:28,973 - INFO - Fiche fermée (desktop).
2025-08-14 09:58:32,472 - INFO - Données sauvegardées dans google_maps_Restaurants_Paris_20250814_095832.xlsx (1 entrées valides)
2025-08-14 09:59:09,086 - INFO - Recherche: Restaurants à Paris
2025-08-14 09:59:18,768 - INFO - 1/2: Eiffel Croisières - Péniche Ivoire
2025-08-14 09:59:18,835 - INFO - Fiche fermée (desktop).
2025-08-14 09:59:23,926 - WARNING - Liste non réapparue, saut forcé
2025-08-14 09:59:27,084 - INFO - Données sauvegardées dans google_maps_Restaurants_Paris_20250814_095926.xlsx (1 entrées valides)
2025-08-14 10:10:29,354 - INFO - Recherche: Restaurants à Paris
2025-08-14 10:11:55,248 - INFO - Recherche: Restaurants à Paris
2025-08-14 10:12:04,542 - INFO - 1/2: Eiffel Croisières - Péniche Ivoire
2025-08-14 10:12:05,580 - WARNING - Impossible de fermer la fiche : Message: element click intercepted: Element <button class="yAuNSb vF7Cdb" jsaction="omnibox.clear; mouseover:omnibox.showTooltip; mouseout:omnibox.hideTooltip; focus:omnibox.showTooltip; blur:omnibox.hideTooltip" aria-label="Fermer">...</button> is not clickable at point (329, 25). Other element would receive the click: <a class="gb_B" aria-label="Applications Google" guidedhelpid="gbawb" href="https://www.google.tn/intl/fr/about/products?tab=lh" aria-expanded="false" role="button" tabindex="0">...</a>
  (Session info: chrome=139.0.7258.68); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception
Stacktrace:
	GetHandleVerifier [0x0xa2fd33+62915]
	GetHandleVerifier [0x0xa2fd74+62980]
	(No symbol) [0x0x863e13]
	(No symbol) [0x0x8b2be0]
	(No symbol) [0x0x8b0f9a]
	(No symbol) [0x0x8aeaf7]
	(No symbol) [0x0x8addb4]
	(No symbol) [0x0x8a2565]
	(No symbol) [0x0x8d13dc]
	(No symbol) [0x0x8a1ff4]
	(No symbol) [0x0x8d1654]
	(No symbol) [0x0x8f26ea]
	(No symbol) [0x0x8d11d6]
	(No symbol) [0x0x8a0833]
	(No symbol) [0x0x8a16a4]
	GetHandleVerifier [0x0xc98d23+2590131]
	GetHandleVerifier [0x0xc93f6a+2570234]
	GetHandleVerifier [0x0xa559ea+217722]
	GetHandleVerifier [0x0xa46058+153832]
	GetHandleVerifier [0x0xa4c4bd+179533]
	GetHandleVerifier [0x0xa37738+94152]
	GetHandleVerifier [0x0xa378c2+94546]
	GetHandleVerifier [0x0xa22bda+9322]
	BaseThreadInitThunk [0x0x761ffcc9+25]
	RtlGetAppContainerNamedObjectPath [0x0x770882ae+286]
	RtlGetAppContainerNamedObjectPath [0x0x7708827e+238]

2025-08-14 10:12:05,582 - WARNING - Saut de l'élément 1 (fermeture impossible)
2025-08-14 10:12:08,910 - INFO - Données sauvegardées dans google_maps_Restaurants_Paris_20250814_101208.xlsx (1 entrées valides)
2025-08-14 10:12:57,473 - INFO - Recherche: Restaurants à Paris
2025-08-14 10:13:06,644 - INFO - 1/2: Eiffel Croisières - Péniche Ivoire
2025-08-14 10:13:06,719 - INFO - Retour à la liste (mobile).
2025-08-14 10:13:10,968 - INFO - 2/2: Vita Ristorante
2025-08-14 10:13:11,012 - INFO - Retour à la liste (mobile).
2025-08-14 10:13:14,648 - INFO - Données sauvegardées dans google_maps_Restaurants_Paris_20250814_101314.xlsx (2 entrées valides)
2025-08-14 10:32:32,910 - INFO - Recherche: Restaurants à Paris
2025-08-14 10:32:45,018 - INFO - 1/2: Eiffel Croisières - Péniche Ivoire
2025-08-14 10:32:45,084 - INFO - Retour à la liste (mobile).
2025-08-14 10:32:49,810 - INFO - 2/2: L'Osteria Paris Chatelet
2025-08-14 10:32:49,856 - INFO - Retour à la liste (mobile).
2025-08-14 10:56:17,254 - INFO - Recherche: Restaurants à 75
2025-08-14 10:56:44,305 - ERROR - Timeout en attente des résultats
2025-08-14 10:57:55,874 - INFO - Recherche: Restaurants à 75
2025-08-14 11:02:11,164 - INFO - Recherche: Restaurants à 75
2025-08-14 11:05:52,824 - INFO - Recherche: Restaurants à Paris
2025-08-14 11:06:05,048 - INFO - 1/2: Eiffel Croisières - Péniche Ivoire
2025-08-14 11:06:05,102 - INFO - Retour à la liste (mobile).
2025-08-14 11:06:09,539 - INFO - 2/2: Vita Ristorante
2025-08-14 11:06:09,583 - INFO - Retour à la liste (mobile).
2025-08-14 11:07:17,701 - INFO - Lancement du scraping pour Restaurants à Paris
2025-08-14 11:07:38,765 - INFO - Extrait: Ty Louis | Tel: 06 73 08 54 13
2025-08-14 11:07:40,917 - INFO - Extrait: Le Caveau de l'Isle | Tel: 01 43 25 10 26
2025-08-14 11:08:30,205 - INFO - Lancement du scraping pour Restaurants à Paris
2025-08-14 11:08:54,668 - INFO - Extrait: Café du Commerce | Tel: 07 72 17 02 88
2025-08-14 11:08:56,821 - INFO - Extrait: Grand Zino | Tel: 01 44 40 45 10, 01 45 78 92 37
2025-08-14 11:13:20,188 - INFO - Recherche: Restaurants à Paris
2025-08-14 11:13:30,092 - INFO - 1/5: Vita Ristorante
2025-08-14 11:13:30,165 - INFO - Retour à la liste (mobile).
2025-08-14 11:13:34,166 - INFO - 2/5: Hôtel Bachaumont
2025-08-14 11:13:34,212 - INFO - Retour à la liste (mobile).
2025-08-14 11:13:38,956 - INFO - 3/5: Le Tout-Paris
2025-08-14 11:13:39,015 - INFO - Retour à la liste (mobile).
2025-08-14 11:13:43,589 - INFO - 4/5: Le Ju'
2025-08-14 11:13:43,646 - INFO - Retour à la liste (mobile).
2025-08-14 11:13:48,596 - INFO - 5/5: Le Marais Restaurant Paris
2025-08-14 11:13:48,647 - INFO - Retour à la liste (mobile).
2025-08-14 11:23:40,674 - INFO - Recherche: restaurants à Paris
2025-08-14 11:23:49,036 - INFO - 1/5: Eiffel Croisières - Péniche Ivoire
2025-08-14 11:23:49,110 - INFO - Retour à la liste (mobile).
2025-08-14 11:23:53,311 - INFO - 2/5: La Maison Favart
2025-08-14 11:23:53,357 - INFO - Retour à la liste (mobile).
2025-08-14 11:23:57,688 - INFO - 3/5: Le Tout-Paris
2025-08-14 11:23:57,733 - INFO - Retour à la liste (mobile).
2025-08-14 11:24:02,073 - INFO - 4/5: Le Ju'
2025-08-14 11:24:02,121 - INFO - Retour à la liste (mobile).
2025-08-14 11:24:06,852 - INFO - 5/5: Le Marais Restaurant Paris
2025-08-14 11:24:06,899 - INFO - Retour à la liste (mobile).
2025-08-14 11:35:24,735 - INFO - Recherche: restaurants à Paris
2025-08-14 11:35:36,705 - INFO - 1/5: Eiffel Croisières - Péniche Ivoire
2025-08-14 11:35:36,760 - INFO - Retour à la liste (mobile).
2025-08-14 11:35:41,360 - INFO - 2/5: Le Tout-Paris
2025-08-14 11:35:41,406 - INFO - Retour à la liste (mobile).
2025-08-14 11:35:45,894 - INFO - 3/5: Le Ju'
2025-08-14 11:35:45,942 - INFO - Retour à la liste (mobile).
2025-08-14 11:35:50,464 - INFO - 4/5: Le Marais Restaurant Paris
2025-08-14 11:35:50,511 - INFO - Retour à la liste (mobile).
2025-08-14 11:35:55,168 - INFO - 5/5: Bouillon République
2025-08-14 11:35:55,213 - INFO - Retour à la liste (mobile).
2025-08-14 12:03:07,895 - INFO - Recherche: Restaurants et services de restauration mobile à Paris
2025-08-14 12:03:16,903 - INFO - 1/5: Delistreet - Food Truck Paris - Location camion restaurant pour evenements : Anniversaire / Mariage / Brunch
2025-08-14 12:03:16,971 - INFO - Retour à la liste (mobile).
2025-08-14 12:03:21,124 - INFO - 2/5: Restaurant Bus Toqué Paris
2025-08-14 12:03:21,169 - INFO - Retour à la liste (mobile).
2025-08-14 12:03:25,839 - INFO - 3/5: Paris Resto Cuisines
2025-08-14 12:03:25,890 - INFO - Retour à la liste (mobile).
2025-08-14 12:03:30,331 - INFO - 4/5: Restaurant Kum Po
2025-08-14 12:03:30,391 - INFO - Retour à la liste (mobile).
2025-08-14 12:03:34,681 - INFO - 5/5: Meshuga
2025-08-14 12:03:34,723 - INFO - Retour à la liste (mobile).
2025-08-14 12:19:07,352 - INFO - Recherche: Culture et production animale, chasse et services annexes à Paris
2025-08-14 12:20:15,966 - INFO - Recherche: Restauration à Paris
2025-08-14 12:20:27,510 - INFO - 1/5: Hôtel Bachaumont
2025-08-14 12:20:27,566 - INFO - Retour à la liste (mobile).
2025-08-14 12:20:32,310 - INFO - 2/5: Le Ju'
2025-08-14 12:20:32,374 - INFO - Retour à la liste (mobile).
2025-08-14 12:20:36,957 - INFO - 3/5: Au Pied de Cochon
2025-08-14 12:20:37,001 - INFO - Retour à la liste (mobile).
2025-08-14 12:20:41,343 - INFO - 4/5: Le Marais Restaurant Paris
2025-08-14 12:20:41,389 - INFO - Retour à la liste (mobile).
2025-08-14 12:20:46,300 - INFO - 5/5: CRISPY SOUL Paris 2
2025-08-14 12:20:46,348 - INFO - Retour à la liste (mobile).
2025-08-14 12:42:31,441 - INFO - Recherche: Cultures permanentes à Paris
2025-08-14 12:44:01,678 - INFO - Recherche: Restaurants et services de restauration mobile à Paris
2025-08-14 12:44:12,032 - INFO - 1/3: Delistreet - Food Truck Paris - Location camion restaurant pour evenements : Anniversaire / Mariage / Brunch
2025-08-14 12:44:12,113 - INFO - Retour à la liste (mobile).
2025-08-14 12:44:16,046 - INFO - 2/3: FNF Restaurant
2025-08-14 12:44:16,090 - INFO - Retour à la liste (mobile).
2025-08-14 12:44:20,614 - INFO - 3/3: Restaurant Bus Toqué Paris
2025-08-14 12:44:20,657 - INFO - Retour à la liste (mobile).
2025-08-14 12:46:22,287 - INFO - Recherche: Restaurants à Paris
2025-08-14 12:46:32,850 - INFO - 1/1: IDA by Denny Imbroisi
2025-08-14 12:46:32,940 - INFO - Retour à la liste (mobile).
2025-08-14 13:01:35,471 - INFO - Recherche: Restauration à Paris
2025-08-14 13:01:46,688 - INFO - 1/1: Hôtel Bachaumont
2025-08-14 13:01:46,768 - INFO - Retour à la liste (mobile).
2025-08-14 14:03:58,827 - INFO - Lancement du scraping pour Restauration à Paris
2025-08-14 14:04:33,328 - INFO - Extrait: Café le Marivaux | Tel: 01 42 96 40 66, 09 67 41 40 66
2025-08-14 14:12:44,702 - INFO - Recherche:  à 
2025-08-14 14:13:10,140 - ERROR - Timeout en attente des résultats
2025-08-14 14:13:29,515 - INFO - Recherche: Restauration à Paris
2025-08-14 14:13:39,905 - INFO - 1/5: La Maison Favart
2025-08-14 14:13:39,988 - INFO - Retour à la liste (mobile).
2025-08-14 14:13:44,721 - INFO - 2/5: the friendly kitchen
2025-08-14 14:13:44,779 - INFO - Retour à la liste (mobile).
2025-08-14 14:13:49,831 - INFO - 3/5: Au Pied de Cochon
2025-08-14 14:13:49,877 - INFO - Retour à la liste (mobile).
2025-08-14 14:13:54,424 - INFO - 4/5: CRISPY SOUL Paris 2
2025-08-14 14:13:54,471 - INFO - Retour à la liste (mobile).
2025-08-14 14:13:59,178 - INFO - 5/5: Le Marais Restaurant Paris
2025-08-14 14:13:59,225 - INFO - Retour à la liste (mobile).
2025-08-14 14:24:06,749 - INFO - Lancement du scraping pour Restauration à Paris
2025-08-14 14:24:37,402 - INFO - Extrait: Le 59 | Tel: 01 80 50 00 29
2025-08-14 14:24:39,539 - INFO - Extrait: Café du Commerce | Tel: 07 72 17 02 88
2025-08-14 14:24:41,674 - INFO - Extrait: Le Caveau de l'Isle | Tel: 01 43 25 10 26
2025-08-14 14:24:43,813 - INFO - Extrait: Café le Marivaux | Tel: 01 42 96 40 66, 09 67 41 40 66
2025-08-14 14:24:45,952 - INFO - Extrait: L'Entracte | Tel: 01 47 42 26 25
2025-08-14 14:28:13,710 - INFO - Lancement du scraping pour Restaurants et services de restauration mobile à Paris
2025-08-14 14:28:34,117 - INFO - Extrait: L'atelier Du Pressing | Tel: 01 45 57 65 87
2025-08-14 14:28:36,254 - INFO - Extrait: Artisans Services Plus | Tel: 01 40 05 19 20
2025-08-14 14:28:52,278 - INFO - Lancement du scraping pour Restaurants et services de restauration mobile à Paris
2025-08-14 14:29:09,972 - INFO - Extrait: EF Education First | Tel:      16     01 42 61 46 26
2025-08-14 14:29:12,122 - INFO - Extrait: France Service Plus | Tel: 01 44 75 79 99
2025-08-14 14:32:25,091 - INFO - Lancement du scraping pour Restaurants et services de restauration mobile à Paris
2025-08-14 14:32:46,773 - INFO - Extrait: L'atelier Du Pressing | Tel: 01 45 57 65 87
2025-08-14 14:32:48,932 - INFO - Extrait: France Service Plus | Tel: 01 44 75 79 99
2025-08-14 14:35:01,959 - INFO - Lancement du scraping pour Restauration à Paris
2025-08-14 14:35:25,355 - INFO - Extrait: Ty Louis | Tel: 06 73 08 54 13
2025-08-14 14:35:27,514 - INFO - Extrait: Le Moghol | Tel: 01 40 06 90 36
2025-08-14 14:35:29,666 - INFO - Extrait: Espace Aurore | Tel: 01 53 94 51 00, 01 53 94 51 02
2025-08-14 14:35:31,812 - INFO - Extrait: Grand Zino | Tel: 01 44 40 45 10, 01 45 78 92 37
2025-08-14 14:35:33,948 - INFO - Extrait: L'Entracte | Tel: 01 47 42 26 25
2025-08-14 14:38:27,501 - INFO - Recherche: Restauration à Paris
2025-08-14 14:38:37,901 - INFO - 1/5: the friendly kitchen
2025-08-14 14:38:37,970 - INFO - Retour à la liste (mobile).
2025-08-14 14:38:42,491 - INFO - 2/5: Brasserie des Arts
2025-08-14 14:38:42,537 - INFO - Retour à la liste (mobile).
2025-08-14 14:38:47,005 - INFO - 3/5: Le Ju'
2025-08-14 14:38:47,051 - INFO - Retour à la liste (mobile).
2025-08-14 14:38:52,206 - INFO - 4/5: Au Pied de Cochon
2025-08-14 14:38:52,256 - INFO - Retour à la liste (mobile).
2025-08-14 14:38:56,968 - INFO - 5/5: Le Marais Restaurant Paris
2025-08-14 14:38:57,015 - INFO - Retour à la liste (mobile).
2025-08-14 14:42:43,444 - INFO - Recherche: Restauration à Paris
2025-08-14 14:42:55,158 - INFO - 1/3: Le Paname Art Café
2025-08-14 14:42:55,212 - INFO - Retour à la liste (mobile).
2025-08-14 14:42:59,738 - INFO - 2/3: Vita Ristorante
2025-08-14 14:42:59,786 - INFO - Retour à la liste (mobile).
2025-08-14 14:43:04,244 - INFO - 3/3: Le Ju'
2025-08-14 14:43:04,290 - INFO - Retour à la liste (mobile).
2025-08-14 15:19:33,767 - INFO - Recherche: Restauration à PARIS 01
2025-08-14 15:19:44,606 - INFO - 1/5: Eiffel Croisières - Péniche Ivoire
2025-08-14 15:19:44,662 - INFO - Retour à la liste (mobile).
2025-08-14 15:19:49,644 - INFO - 2/5: Hôtel Bachaumont
2025-08-14 15:19:49,706 - INFO - Retour à la liste (mobile).
2025-08-14 15:19:54,223 - INFO - 3/5: Au Pied de Cochon
2025-08-14 15:19:54,269 - INFO - Retour à la liste (mobile).
2025-08-14 15:19:58,559 - INFO - 4/5: Le Tout-Paris
2025-08-14 15:19:58,605 - INFO - Retour à la liste (mobile).
2025-08-14 15:20:03,509 - INFO - 5/5: COME PRIMA by OSKIAN Restaurant Italien Paris 1
2025-08-14 15:20:03,559 - INFO - Retour à la liste (mobile).
2025-08-14 15:50:58,733 - INFO - Recherche: Restauration à Aisne
2025-08-14 15:51:10,740 - INFO - 1/5: La Table des Saveurs
2025-08-14 15:51:10,799 - INFO - Retour à la liste (mobile).
2025-08-14 15:51:15,057 - INFO - 2/5: Restaurant le Péché Mignon
2025-08-14 15:51:15,101 - INFO - Retour à la liste (mobile).
2025-08-14 15:51:19,364 - INFO - 3/5: Chez Jeannot
2025-08-14 15:51:19,420 - INFO - Retour à la liste (mobile).
2025-08-14 15:51:23,942 - INFO - 4/5: Donjon Uerl
2025-08-14 15:51:23,999 - INFO - Retour à la liste (mobile).
2025-08-14 15:51:28,351 - INFO - 5/5: Restaurant La Passerelle
2025-08-14 15:51:28,396 - INFO - Retour à la liste (mobile).
2025-08-14 15:53:55,692 - INFO - Recherche: Débits de boissons à Centre-Val de Loire
2025-08-14 15:54:23,533 - ERROR - Timeout en attente des résultats
2025-08-14 16:13:38,707 - INFO - Recherche: Débits de boissons à CHARTRES
2025-08-14 16:13:49,428 - INFO - 1/5: V and B Chartres
2025-08-14 16:13:49,485 - INFO - Retour à la liste (mobile).
2025-08-14 16:13:54,055 - INFO - 2/5: Brasserie Delabonne - Vente Fût de bière & Location Tireuse à bière - Chartres
2025-08-14 16:13:54,096 - INFO - Retour à la liste (mobile).
2025-08-14 16:13:58,794 - INFO - 3/5: Chartres boissons
2025-08-14 16:13:58,832 - INFO - Retour à la liste (mobile).
2025-08-14 16:14:03,450 - INFO - 4/5: Chope et Compagnie Chartres
2025-08-14 16:14:03,489 - INFO - Retour à la liste (mobile).
2025-08-14 16:14:07,888 - INFO - 5/5: Cave St Lubin
2025-08-14 16:14:07,927 - INFO - Retour à la liste (mobile).
2025-08-14 16:14:59,295 - INFO - Recherche: Débits de boissons à Alpes-de-Haute-Provence
2025-08-14 16:15:24,993 - ERROR - Timeout en attente des résultats
2025-08-14 16:17:49,133 - INFO - Recherche: Débits de boissons à Paris
2025-08-14 16:18:53,152 - INFO - Recherche: Débits de boissons à Paris
2025-08-14 16:20:24,499 - INFO - Recherche: Débits de boissons à paris
2025-08-14 16:46:32,657 - INFO - --- Recherche pour mot-clé: debits de boissons ---
2025-08-14 16:46:34,578 - INFO - Recherche: debits de boissons à Ain
2025-08-14 16:47:01,827 - ERROR - Timeout en attente des résultats
2025-08-14 16:47:03,916 - INFO - --- Recherche pour mot-clé: débits de boissons ---
2025-08-14 16:47:05,596 - INFO - Recherche: débits de boissons à Ain
2025-08-14 16:47:56,869 - INFO - 1/5: Ain
2025-08-14 16:47:56,919 - INFO - Retour à la liste (mobile).
2025-08-14 16:49:00,640 - INFO - --- Recherche pour mot-clé: debits de boissons ---
2025-08-14 16:49:02,368 - INFO - Recherche: debits de boissons à Ain
2025-08-14 16:49:30,516 - ERROR - Timeout en attente des résultats
2025-08-14 16:49:32,596 - INFO - --- Recherche pour mot-clé: débits de boissons ---
2025-08-14 16:49:34,341 - INFO - Recherche: débits de boissons à Ain
2025-08-14 16:50:25,926 - INFO - 1/5: Ain
2025-08-14 16:50:25,970 - INFO - Retour à la liste (mobile).
2025-08-14 16:52:02,791 - INFO - --- Recherche pour mot-clé: debits de boissons ---
2025-08-14 16:52:04,591 - INFO - Recherche: debits de boissons à Ain
2025-08-14 16:52:31,108 - ERROR - Timeout en attente des résultats
2025-08-14 16:52:33,190 - INFO - --- Recherche pour mot-clé: débits de boissons ---
2025-08-14 16:52:34,941 - INFO - Recherche: débits de boissons à Ain
2025-08-14 16:53:24,216 - INFO - 1/5: Ain
2025-08-14 16:53:24,262 - INFO - Retour à la liste (mobile).
2025-08-14 16:54:10,882 - INFO - --- Recherche pour mot-clé: 56.30Z ---
2025-08-14 16:54:12,686 - INFO - Recherche: 56.30Z à Ain
2025-08-14 16:55:02,981 - INFO - 1/5: Ain
2025-08-14 16:55:03,031 - INFO - Retour à la liste (mobile).
2025-08-14 16:55:47,313 - INFO - --- Recherche pour mot-clé: 56.30Z ---
2025-08-14 16:55:49,099 - INFO - Recherche: 56.30Z à Paris
2025-08-14 16:56:16,649 - INFO - --- Recherche pour mot-clé: debits de boissons ---
2025-08-14 16:56:18,385 - INFO - Recherche: debits de boissons à Ain
2025-08-14 16:56:38,889 - INFO - 1/5: Paris
2025-08-14 16:56:38,938 - INFO - Retour à la liste (mobile).
2025-08-14 16:56:45,872 - ERROR - Timeout en attente des résultats
2025-08-14 16:56:47,948 - INFO - --- Recherche pour mot-clé: débits de boissons ---
2025-08-14 16:56:49,622 - INFO - Recherche: débits de boissons à Ain
2025-08-14 16:57:39,120 - INFO - 1/5: Ain
2025-08-14 16:57:39,170 - INFO - Retour à la liste (mobile).
2025-08-14 16:57:58,207 - INFO - Lancement du scraping pour Débits de boissons à Ain
2025-08-14 16:58:18,833 - INFO - Extrait: La Terrasse | Tel: 04 72 26 10 33
2025-08-14 16:58:20,979 - INFO - Extrait: Le Français | Tel: 04 74 22 55 14
2025-08-14 16:58:23,132 - INFO - Extrait: La Réserve | Tel: 04 74 73 44 84
2025-08-14 16:58:25,268 - INFO - Extrait: La Bicyclette Bleue | Tel:     04 74 98 21 48
2025-08-14 16:58:27,410 - INFO - Extrait: Le Chaudron | Tel:     04 74 00 43 52
2025-08-14 16:59:59,609 - INFO - --- Recherche pour mot-clé: debits de boissons ---
2025-08-14 17:00:01,723 - INFO - Recherche: debits de boissons à Paris
2025-08-14 17:00:14,503 - INFO - 1/5: Aventum
2025-08-14 17:00:14,554 - INFO - Retour à la liste (mobile).
2025-08-14 17:00:19,329 - INFO - 2/5: Gilgamesh Bar a Vin
2025-08-14 17:00:19,370 - INFO - Retour à la liste (mobile).
2025-08-14 17:00:23,667 - INFO - 3/5: Centrale Boissons (Siège social)
2025-08-14 17:00:23,709 - INFO - Retour à la liste (mobile).
2025-08-14 17:00:28,351 - INFO - 4/5: Bistrot du bar
2025-08-14 17:00:28,395 - INFO - Retour à la liste (mobile).
2025-08-14 17:00:33,723 - INFO - 5/5: Le paris bar
2025-08-14 17:00:33,767 - INFO - Retour à la liste (mobile).
2025-08-14 17:00:37,369 - INFO - --- Recherche pour mot-clé: débits de boissons ---
2025-08-14 17:00:39,107 - INFO - Recherche: débits de boissons à Paris
2025-08-14 17:00:50,313 - INFO - 1/5: Comptoir MONIN
2025-08-14 17:00:50,364 - INFO - Retour à la liste (mobile).
2025-08-14 17:00:54,697 - INFO - 2/5: Gilgamesh Bar a Vin
2025-08-14 17:00:54,738 - INFO - Retour à la liste (mobile).
2025-08-14 17:00:59,275 - INFO - 3/5: Centrale Boissons (Siège social)
2025-08-14 17:00:59,320 - INFO - Retour à la liste (mobile).
2025-08-14 17:01:03,623 - INFO - 4/5: SODIMAC distributeurs automatiques
2025-08-14 17:01:03,666 - INFO - Retour à la liste (mobile).
2025-08-14 17:01:08,113 - INFO - 5/5: Paris Boissons
2025-08-14 17:01:08,158 - INFO - Retour à la liste (mobile).
2025-08-14 17:20:14,541 - INFO - --- Recherche pour mot-clé: debits de boissons ---
2025-08-14 17:20:16,312 - INFO - Recherche: debits de boissons à Paris
2025-08-14 17:20:26,436 - INFO - 1/5: Aventum
2025-08-14 17:20:26,491 - INFO - Retour à la liste (mobile).
2025-08-14 17:20:30,933 - INFO - 2/5: Gilgamesh Bar a Vin
2025-08-14 17:20:30,974 - INFO - Retour à la liste (mobile).
2025-08-14 17:20:35,517 - INFO - 3/5: Centrale Boissons (Siège social)
2025-08-14 17:20:35,558 - INFO - Retour à la liste (mobile).
2025-08-14 17:20:39,904 - INFO - 4/5: Bistrot du bar
2025-08-14 17:20:39,948 - INFO - Retour à la liste (mobile).
2025-08-14 17:20:44,651 - INFO - 5/5: Le paris bar
2025-08-14 17:20:44,700 - INFO - Retour à la liste (mobile).
2025-08-14 17:20:48,870 - INFO - --- Recherche pour mot-clé: débits de boissons ---
2025-08-14 17:20:50,633 - INFO - Recherche: débits de boissons à Paris
2025-08-14 17:28:43,677 - INFO - --- Recherche pour mot-clé: autres activites des medecins specialistes ---
2025-08-14 17:28:45,369 - INFO - Recherche: autres activites des medecins specialistes à Paris
2025-08-14 17:29:12,621 - ERROR - Timeout en attente des résultats
2025-08-14 17:29:14,705 - INFO - --- Recherche pour mot-clé: autres activités des médecins spécialistes ---
2025-08-14 17:29:16,478 - INFO - Recherche: autres activités des médecins spécialistes à Paris
2025-08-14 17:30:08,774 - INFO - 1/5: Paris
2025-08-14 17:30:08,821 - INFO - Retour à la liste (mobile).
2025-08-14 17:35:42,291 - INFO - --- Recherche pour mot-clé: pratique dentaire ---
2025-08-14 17:35:44,041 - INFO - Recherche: pratique dentaire à Ain
2025-08-14 17:39:00,790 - INFO - --- Recherche pour mot-clé: pratique dentaire ---
2025-08-14 17:39:02,473 - INFO - Recherche: pratique dentaire à Ain
2025-08-14 17:40:58,346 - INFO - --- Recherche pour mot-clé: activite des medecins generalistes ---
2025-08-14 17:41:00,104 - INFO - Recherche: activite des medecins generalistes à Ain
2025-08-14 17:41:29,202 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAE9A5FE50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/3030fa1cc49ba29feb0fabf29a85bf25/element
2025-08-14 17:41:33,239 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAE9A5D350>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/3030fa1cc49ba29feb0fabf29a85bf25/element
2025-08-14 17:41:37,270 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAE9A701D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/3030fa1cc49ba29feb0fabf29a85bf25/element
2025-08-14 17:41:41,341 - ERROR - Timeout en attente des résultats
2025-08-14 17:41:45,387 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAE9A72510>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/3030fa1cc49ba29feb0fabf29a85bf25
2025-08-14 17:41:49,436 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAE9A72BD0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/3030fa1cc49ba29feb0fabf29a85bf25
2025-08-14 17:41:53,478 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CAE9A724D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/3030fa1cc49ba29feb0fabf29a85bf25
2025-08-14 17:43:57,615 - INFO - --- Recherche pour mot-clé: 86.23Z ---
2025-08-14 17:43:59,464 - INFO - Recherche: 86.23Z à Ain
2025-08-14 17:44:21,784 - INFO - --- Recherche pour mot-clé: pratique dentaire ---
2025-08-14 17:44:23,613 - INFO - Recherche: pratique dentaire à Ain
2025-08-14 17:44:49,189 - INFO - 1/5: Ain
2025-08-14 17:44:49,230 - INFO - Retour à la liste (mobile).
2025-08-14 17:52:50,933 - INFO - --- Recherche pour mot-clé: médecin spécialiste ---
2025-08-14 17:52:52,816 - INFO - Recherche: médecin spécialiste à Ain
2025-08-14 17:54:18,836 - INFO - --- Recherche pour mot-clé: spécialiste ---
2025-08-14 17:54:20,531 - INFO - Recherche: spécialiste à Ain
2025-08-14 17:55:47,829 - INFO - --- Recherche pour mot-clé: cabinet médical ---
2025-08-14 17:55:49,544 - INFO - Recherche: cabinet médical à Ain
2025-08-14 17:56:37,720 - INFO - --- Recherche pour mot-clé: cardiologue ---
2025-08-14 17:56:39,445 - INFO - Recherche: cardiologue à Ain
2025-08-14 17:57:28,725 - INFO - --- Recherche pour mot-clé: dermatologue ---
2025-08-14 17:57:30,426 - INFO - Recherche: dermatologue à Ain
2025-08-14 17:57:51,169 - INFO - --- Recherche pour mot-clé: médecin spécialiste ---
2025-08-14 17:57:52,942 - INFO - Recherche: médecin spécialiste à Ain
2025-08-14 17:58:22,883 - INFO - --- Recherche pour mot-clé: ophtalmologue ---
2025-08-14 17:58:24,645 - INFO - Recherche: ophtalmologue à Ain
2025-08-14 17:59:19,638 - INFO - --- Recherche pour mot-clé: spécialiste ---
2025-08-14 17:59:21,351 - INFO - Recherche: spécialiste à Ain
2025-08-14 18:00:50,216 - INFO - --- Recherche pour mot-clé: cabinet médical ---
2025-08-14 18:00:51,961 - INFO - Recherche: cabinet médical à Ain
2025-08-14 18:01:06,621 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002759B2C8F10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/bc99c75f58e297c9aa0f56dfbb686b0b/execute/sync
2025-08-14 18:01:10,668 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002759B2D1F50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/bc99c75f58e297c9aa0f56dfbb686b0b/execute/sync
2025-08-14 18:01:14,715 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002759B2F2550>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/bc99c75f58e297c9aa0f56dfbb686b0b/execute/sync
2025-08-14 18:01:18,763 - ERROR - Erreur majeure: HTTPConnectionPool(host='localhost', port=49921): Max retries exceeded with url: /session/bc99c75f58e297c9aa0f56dfbb686b0b/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002759B2F2790>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 493, in _make_request
    conn.request(
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 494, in request
    self.endheaders()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 325, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002759B2F2790>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 166, in scrape_google_maps
    scroll_to_load_results(driver, max_results)
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 103, in scroll_to_load_results
    current_height = driver.execute_script("""
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 555, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in execute
    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 406, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 430, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 459, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49921): Max retries exceeded with url: /session/bc99c75f58e297c9aa0f56dfbb686b0b/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002759B2F2790>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-08-14 18:01:22,915 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002759B2F2C10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/bc99c75f58e297c9aa0f56dfbb686b0b
2025-08-14 18:01:26,960 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002759B7D1B50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/bc99c75f58e297c9aa0f56dfbb686b0b
2025-08-14 18:01:31,009 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002759B7D21D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/bc99c75f58e297c9aa0f56dfbb686b0b
2025-08-14 18:01:35,055 - INFO - --- Recherche pour mot-clé: cardiologue ---
2025-08-14 18:01:36,736 - INFO - Recherche: cardiologue à Ain
2025-08-14 18:01:38,323 - ERROR - Erreur majeure: ('Connection aborted.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))
Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1378, in getresponse
    response.begin()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 160, in scrape_google_maps
    driver.get(url)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 483, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in execute
    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 406, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 430, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 459, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 565, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1378, in getresponse
    response.begin()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))
2025-08-15 09:06:51,391 - INFO - --- Recherche pour mot-clé: debits de boissons ---
2025-08-15 09:06:56,365 - INFO - Recherche: debits de boissons à Ain
2025-08-15 09:07:23,433 - ERROR - Timeout en attente des résultats
2025-08-15 09:07:25,546 - INFO - --- Recherche pour mot-clé: débits de boissons ---
2025-08-15 09:07:27,308 - INFO - Recherche: débits de boissons à Ain
2025-08-15 09:08:18,253 - INFO - 1/5: Ain
2025-08-15 09:08:18,298 - INFO - Retour à la liste (mobile).
2025-08-15 09:08:50,096 - INFO - --- Recherche pour mot-clé: debits de boissons ---
2025-08-15 09:08:51,756 - INFO - Recherche: debits de boissons à Ain
2025-08-15 09:09:18,559 - ERROR - Timeout en attente des résultats
2025-08-15 09:09:20,618 - INFO - --- Recherche pour mot-clé: débits de boissons ---
2025-08-15 09:09:22,311 - INFO - Recherche: débits de boissons à Ain
2025-08-15 09:10:10,796 - INFO - 1/5: Ain
2025-08-15 09:10:10,841 - INFO - Retour à la liste (mobile).
2025-08-15 09:10:30,788 - INFO - --- Recherche pour mot-clé: café bar ---
2025-08-15 09:10:32,623 - INFO - Recherche: café bar à Ain
2025-08-15 09:11:17,862 - INFO - --- Recherche pour mot-clé: brasserie ---
2025-08-15 09:11:19,510 - INFO - Recherche: brasserie à Ain
2025-08-15 09:11:28,577 - INFO - 1/5: La Bressane - Brasserie Saint Clair
2025-08-15 09:11:28,641 - INFO - Retour à la liste (mobile).
2025-08-15 09:11:32,758 - INFO - 2/5: Brasserie l'Ain Pression - Malt Emoi
2025-08-15 09:11:32,802 - INFO - Retour à la liste (mobile).
2025-08-15 09:11:37,312 - INFO - 3/5: Rivière d'Ain (Brasserie artisanale)
2025-08-15 09:11:37,355 - INFO - Retour à la liste (mobile).
2025-08-15 09:11:41,756 - INFO - 4/5: Brasserie l'Etincelle
2025-08-15 09:11:41,798 - INFO - Retour à la liste (mobile).
2025-08-15 09:11:46,062 - INFO - 5/5: Brasserie Grange Noire
2025-08-15 09:11:46,104 - INFO - Retour à la liste (mobile).
2025-08-15 09:11:49,771 - INFO - --- Recherche pour mot-clé: caviste ---
2025-08-15 09:11:51,493 - INFO - Recherche: caviste à Ain
2025-08-15 09:12:42,265 - INFO - 1/5: Cave du Val d'Or
2025-08-15 09:12:42,318 - INFO - Retour à la liste (mobile).
2025-08-15 09:12:46,861 - INFO - 2/5: La Cave d'August
2025-08-15 09:12:46,904 - INFO - Retour à la liste (mobile).
2025-08-15 09:12:51,188 - INFO - 3/5: Epicerie & Cave Chez Nathalie - Vente et Dégustation
2025-08-15 09:12:51,234 - INFO - Retour à la liste (mobile).
2025-08-15 09:12:54,986 - INFO - --- Recherche pour mot-clé: caféteria ---
2025-08-15 09:12:56,699 - INFO - Recherche: caféteria à Ain
2025-08-15 09:16:35,777 - INFO - --- Recherche pour mot-clé: médecin spécialiste ---
2025-08-15 09:16:38,415 - INFO - Recherche: médecin spécialiste à Ain
2025-08-15 09:16:54,253 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA0DD301D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/dee4ec3ef19a81950a2b4c5c65937660/execute/sync
2025-08-15 09:16:58,329 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA0DD31910>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/dee4ec3ef19a81950a2b4c5c65937660/execute/sync
2025-08-15 09:17:02,394 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA0DD33310>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/dee4ec3ef19a81950a2b4c5c65937660/execute/sync
2025-08-15 09:17:06,455 - ERROR - Erreur majeure: HTTPConnectionPool(host='localhost', port=63136): Max retries exceeded with url: /session/dee4ec3ef19a81950a2b4c5c65937660/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA0DD31F10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 493, in _make_request
    conn.request(
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 494, in request
    self.endheaders()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 325, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001DA0DD31F10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 166, in scrape_google_maps
    scroll_to_load_results(driver, max_results)
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 103, in scroll_to_load_results
    current_height = driver.execute_script("""
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 555, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in execute
    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 406, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 430, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 459, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=63136): Max retries exceeded with url: /session/dee4ec3ef19a81950a2b4c5c65937660/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA0DD31F10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-08-15 09:17:10,633 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA0DD32710>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/dee4ec3ef19a81950a2b4c5c65937660
2025-08-15 09:17:48,606 - INFO - --- Recherche pour mot-clé: médecin spécialiste ---
2025-08-15 09:17:50,311 - INFO - Recherche: médecin spécialiste à Ain
2025-08-15 09:19:14,335 - INFO - --- Recherche pour mot-clé: spécialiste ---
2025-08-15 09:19:16,022 - INFO - Recherche: spécialiste à Ain
2025-08-15 09:20:48,606 - INFO - --- Recherche pour mot-clé: cabinet médical ---
2025-08-15 09:20:50,322 - INFO - Recherche: cabinet médical à Ain
2025-08-15 09:21:39,898 - INFO - --- Recherche pour mot-clé: cardiologue ---
2025-08-15 09:21:41,550 - INFO - Recherche: cardiologue à Ain
2025-08-15 09:22:30,857 - INFO - --- Recherche pour mot-clé: dermatologue ---
2025-08-15 09:22:32,597 - INFO - Recherche: dermatologue à Ain
2025-08-15 09:23:20,323 - INFO - --- Recherche pour mot-clé: ophtalmologue ---
2025-08-15 09:23:21,975 - INFO - Recherche: ophtalmologue à Ain
2025-08-15 09:23:50,995 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9601D6E90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/8af67e5c72eda6839f1a51825fee1c46/execute/sync
2025-08-15 09:23:55,054 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9601D5D10>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/8af67e5c72eda6839f1a51825fee1c46/execute/sync
2025-08-15 09:23:59,127 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B96015F6D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/8af67e5c72eda6839f1a51825fee1c46/execute/sync
2025-08-15 09:24:29,387 - INFO - --- Recherche pour mot-clé: Orthodontiste ---
2025-08-15 09:24:31,082 - INFO - Recherche: Orthodontiste à Ardennes
2025-08-15 09:25:22,551 - INFO - --- Recherche pour mot-clé: Parodontiste ---
2025-08-15 09:25:24,221 - INFO - Recherche: Parodontiste à Ardennes
2025-08-15 09:26:22,518 - INFO - --- Recherche pour mot-clé: Chirurgien dentiste ---
2025-08-15 09:26:24,206 - INFO - Recherche: Chirurgien dentiste à Ardennes
2025-08-15 09:36:45,136 - INFO - Recherche: Pratique dentaire à Ardennes
2025-08-15 09:43:55,081 - INFO - Recherche: Orthodontiste à Ain
2025-08-15 09:44:54,265 - INFO - Recherche: Parodontiste à Ain
2025-08-15 09:45:43,522 - INFO - Recherche: Chirurgien dentiste à Ain
2025-08-15 09:52:56,695 - INFO - --- Recherche pour mot-clé: Orthodontiste ---
2025-08-15 09:52:58,489 - INFO - Recherche: Orthodontiste à Ain
2025-08-15 09:53:55,909 - INFO - --- Recherche pour mot-clé: Parodontiste ---
2025-08-15 09:53:57,579 - INFO - Recherche: Parodontiste à Ain
2025-08-15 09:54:46,957 - INFO - --- Recherche pour mot-clé: Chirurgien dentiste ---
2025-08-15 09:54:48,606 - INFO - Recherche: Chirurgien dentiste à Ain
2025-08-15 10:15:52,603 - INFO - --- Recherche pour mot-clé: Orthodontiste ---
2025-08-15 10:15:55,218 - INFO - Recherche: Orthodontiste à Ain
2025-08-15 10:16:02,620 - ERROR - Timeout en attente des résultats
2025-08-15 10:16:04,737 - INFO - --- Recherche pour mot-clé: Parodontiste ---
2025-08-15 10:16:06,414 - INFO - Recherche: Parodontiste à Ain
2025-08-15 10:16:11,635 - ERROR - Timeout en attente des résultats
2025-08-15 10:16:13,809 - INFO - --- Recherche pour mot-clé: Chirurgien dentiste ---
2025-08-15 10:16:15,462 - INFO - Recherche: Chirurgien dentiste à Ain
2025-08-15 10:16:23,776 - ERROR - Timeout en attente des résultats
2025-08-15 10:16:39,569 - INFO - --- Recherche pour mot-clé: Orthodontiste ---
2025-08-15 10:16:41,299 - INFO - Recherche: Orthodontiste à Ain
2025-08-15 10:17:37,287 - INFO - --- Recherche pour mot-clé: Parodontiste ---
2025-08-15 10:17:39,004 - INFO - Recherche: Parodontiste à Ain
2025-08-15 10:18:25,193 - INFO - --- Recherche pour mot-clé: Chirurgien dentiste ---
2025-08-15 10:18:26,894 - INFO - Recherche: Chirurgien dentiste à Ain
2025-08-15 10:23:05,425 - INFO - --- Recherche pour mot-clé: Orthodontiste ---
2025-08-15 10:23:07,195 - INFO - Recherche: Orthodontiste à Ain
2025-08-15 10:24:05,349 - INFO - --- Recherche pour mot-clé: Parodontiste ---
2025-08-15 10:24:07,000 - INFO - Recherche: Parodontiste à Ain
2025-08-15 10:24:55,283 - INFO - --- Recherche pour mot-clé: Chirurgien dentiste ---
2025-08-15 10:24:57,033 - INFO - Recherche: Chirurgien dentiste à Ain
2025-08-15 10:26:09,646 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8AFD49210>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/94be4fcd59e26d01d26cebeb175022b1/execute/sync
2025-08-15 10:26:13,699 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8AFD49F50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/94be4fcd59e26d01d26cebeb175022b1/execute/sync
2025-08-15 10:26:17,751 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8AFD49DD0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/94be4fcd59e26d01d26cebeb175022b1/execute/sync
2025-08-15 10:26:21,789 - ERROR - Erreur majeure: HTTPConnectionPool(host='localhost', port=49705): Max retries exceeded with url: /session/94be4fcd59e26d01d26cebeb175022b1/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8AFD446D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 493, in _make_request
    conn.request(
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 494, in request
    self.endheaders()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 325, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001B8AFD446D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 165, in scrape_google_maps
    scroll_to_load_results(driver, max_results)
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 105, in scroll_to_load_results
    current_height = driver.execute_script("return arguments[0].scrollHeight;", container)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 555, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in execute
    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 406, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 430, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 459, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49705): Max retries exceeded with url: /session/94be4fcd59e26d01d26cebeb175022b1/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8AFD446D0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-08-15 10:27:07,654 - INFO - --- Recherche pour mot-clé: Restaurants ---
2025-08-15 10:27:09,498 - INFO - Recherche: Restaurants à Paris
2025-08-15 10:27:21,377 - INFO - 1/2: Eiffel Croisières - Péniche Ivoire
2025-08-15 10:27:21,444 - INFO - Retour à la liste (mobile).
2025-08-15 10:27:25,779 - INFO - 2/2: Le Tout-Paris
2025-08-15 10:27:25,826 - INFO - Retour à la liste (mobile).
2025-08-15 10:27:49,206 - INFO - --- Recherche pour mot-clé: café bar ---
2025-08-15 10:27:51,441 - INFO - Recherche: café bar à Paris
2025-08-15 10:28:00,632 - INFO - 1/2: Café de Paris V
2025-08-15 10:28:00,699 - INFO - Retour à la liste (mobile).
2025-08-15 10:28:04,774 - INFO - 2/2: café bar Paris
2025-08-15 10:28:04,817 - INFO - Retour à la liste (mobile).
2025-08-15 10:28:33,200 - INFO - --- Recherche pour mot-clé: Orthodontiste ---
2025-08-15 10:28:34,864 - INFO - Recherche: Orthodontiste à Paris
2025-08-15 10:30:06,833 - INFO - --- Recherche pour mot-clé: Parodontiste ---
2025-08-15 10:30:08,877 - INFO - Recherche: Parodontiste à Paris
2025-08-15 10:31:37,448 - INFO - --- Recherche pour mot-clé: Chirurgien dentiste ---
2025-08-15 10:31:39,120 - INFO - Recherche: Chirurgien dentiste à Paris
2025-08-15 10:37:53,837 - INFO - --- Recherche pour mot-clé: café bar ---
2025-08-15 10:37:55,614 - INFO - Recherche: café bar à Ain
2025-08-15 10:38:07,296 - INFO - 1/5: Café La Sirène
2025-08-15 10:38:07,348 - INFO - Retour à la liste (mobile).
2025-08-15 10:38:11,806 - INFO - 2/5: Aoussou Café Bar
2025-08-15 10:38:11,848 - INFO - Retour à la liste (mobile).
2025-08-15 10:38:16,158 - INFO - 3/5: café bar Paris
2025-08-15 10:38:16,199 - INFO - Retour à la liste (mobile).
2025-08-15 10:38:20,690 - INFO - 4/5: Café resto La Sirène
2025-08-15 10:38:20,731 - INFO - Retour à la liste (mobile).
2025-08-15 10:38:25,091 - INFO - 5/5: Espresso Café Restaurant
2025-08-15 10:38:25,132 - INFO - Retour à la liste (mobile).
2025-08-15 10:38:28,584 - INFO - --- Recherche pour mot-clé: brasserie ---
2025-08-15 10:38:30,307 - INFO - Recherche: brasserie à Ain
2025-08-15 10:38:40,418 - INFO - 1/5: La Bressane - Brasserie Saint Clair
2025-08-15 10:38:40,472 - INFO - Retour à la liste (mobile).
2025-08-15 10:38:45,116 - INFO - 2/5: Brasserie l'Ain Pression - Malt Emoi
2025-08-15 10:38:45,162 - INFO - Retour à la liste (mobile).
2025-08-15 10:38:49,463 - INFO - 3/5: Rivière d'Ain (Brasserie artisanale)
2025-08-15 10:38:49,501 - INFO - Retour à la liste (mobile).
2025-08-15 10:38:54,173 - INFO - 4/5: Brasserie l'Etincelle
2025-08-15 10:38:54,218 - INFO - Retour à la liste (mobile).
2025-08-15 10:38:58,796 - INFO - 5/5: Brasserie Artisanale Piva
2025-08-15 10:38:58,848 - INFO - Retour à la liste (mobile).
2025-08-15 10:39:02,720 - INFO - --- Recherche pour mot-clé: caviste ---
2025-08-15 10:39:04,359 - INFO - Recherche: caviste à Ain
2025-08-15 10:39:14,313 - INFO - 1/5: Cave du Val d'Or
2025-08-15 10:39:14,366 - INFO - Retour à la liste (mobile).
2025-08-15 10:39:18,679 - INFO - 2/5: La Cave d'August
2025-08-15 10:39:18,720 - INFO - Retour à la liste (mobile).
2025-08-15 10:39:23,152 - INFO - 3/5: Epicerie & Cave Chez Nathalie - Vente et Dégustation
2025-08-15 10:39:23,195 - INFO - Retour à la liste (mobile).
2025-08-15 10:39:27,816 - INFO - 4/5: La Cave D ' Epicure
2025-08-15 10:39:27,857 - INFO - Retour à la liste (mobile).
2025-08-15 10:39:32,531 - INFO - 5/5: Cave Bresse Revermont
2025-08-15 10:39:32,575 - INFO - Retour à la liste (mobile).
2025-08-15 10:39:36,800 - INFO - --- Recherche pour mot-clé: caféteria ---
2025-08-15 10:39:38,483 - INFO - Recherche: caféteria à Ain
2025-08-15 10:44:54,942 - INFO - --- Recherche pour mot-clé: café bar ---
2025-08-15 10:44:56,745 - INFO - Recherche: café bar à Ain
2025-08-15 10:45:06,890 - INFO - 1/5: Aoussou Café Bar
2025-08-15 10:45:06,945 - INFO - Retour à la liste (mobile).
2025-08-15 10:45:11,540 - INFO - 2/5: La Fougère - Salon de The & Restaurant Lounge
2025-08-15 10:45:11,583 - INFO - Retour à la liste (mobile).
2025-08-15 10:45:16,270 - INFO - 3/5: Café La Sirène
2025-08-15 10:45:16,311 - INFO - Retour à la liste (mobile).
2025-08-15 10:45:20,588 - INFO - 4/5: café bar Paris
2025-08-15 10:45:20,630 - INFO - Retour à la liste (mobile).
2025-08-15 10:45:24,902 - INFO - 5/5: Espresso Café Restaurant
2025-08-15 10:51:46,906 - INFO - --- Recherche pour mot-clé: Orthodontiste ---
2025-08-15 10:51:48,601 - INFO - Recherche: Orthodontiste à Paris
2025-08-15 10:52:44,458 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000167E7158890>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/4a70330325682efda790b026c6aba056/execute/sync
2025-08-15 10:52:48,526 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000167E715A850>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/4a70330325682efda790b026c6aba056/execute/sync
2025-08-15 10:52:52,582 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000167E715B750>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/4a70330325682efda790b026c6aba056/execute/sync
2025-08-15 10:52:56,611 - ERROR - Erreur majeure: HTTPConnectionPool(host='localhost', port=51517): Max retries exceeded with url: /session/4a70330325682efda790b026c6aba056/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000167E64C9310>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 493, in _make_request
    conn.request(
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 494, in request
    self.endheaders()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 325, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000167E64C9310>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 165, in scrape_google_maps
    scroll_to_load_results(driver, max_results)
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 105, in scroll_to_load_results
    current_height = driver.execute_script("return arguments[0].scrollHeight;", container)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 555, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in execute
    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 406, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 430, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 459, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=51517): Max retries exceeded with url: /session/4a70330325682efda790b026c6aba056/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000167E64C9310>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-08-15 10:53:00,556 - INFO - --- Recherche pour mot-clé: café bar ---
2025-08-15 10:53:02,685 - INFO - Recherche: café bar à Paris
2025-08-15 10:53:12,837 - INFO - 1/2: Café de Paris V
2025-08-15 10:53:12,913 - INFO - Retour à la liste (mobile).
2025-08-15 10:53:16,982 - INFO - 2/2: café bar Paris
2025-08-15 10:53:27,347 - INFO - --- Recherche pour mot-clé: café bar ---
2025-08-15 10:53:29,067 - INFO - Recherche: café bar à Ain
2025-08-15 10:53:38,400 - INFO - 1/2: Aoussou Café Bar
2025-08-15 10:53:38,450 - INFO - Retour à la liste (mobile).
2025-08-15 10:53:42,710 - INFO - 2/2: La Fougère - Salon de The & Restaurant Lounge
2025-08-15 10:54:04,094 - INFO - --- Recherche pour mot-clé: café bar ---
2025-08-15 10:54:05,769 - INFO - Recherche: café bar à Ain
2025-08-15 10:54:15,765 - INFO - 1/2: L'aincontournable
2025-08-15 10:54:15,816 - INFO - Retour à la liste (mobile).
2025-08-15 10:54:20,477 - INFO - 2/2: Café Du Champ De Foire
2025-08-15 11:06:06,275 - INFO - --- Recherche pour mot-clé: dentiste ---
2025-08-15 11:06:08,577 - INFO - Recherche: dentiste à Paris
2025-08-15 11:07:39,802 - INFO - --- Recherche pour mot-clé: cabinet dentaire ---
2025-08-15 11:07:41,547 - INFO - Recherche: cabinet dentaire à Paris
2025-08-15 11:09:08,395 - INFO - --- Recherche pour mot-clé: clinique dentaire ---
2025-08-15 11:09:10,152 - INFO - Recherche: clinique dentaire à Paris
2025-08-15 11:10:08,539 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C801A15010>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/f1aaf4c26ed28ffd8a940eb094f3acdc/execute/sync
2025-08-15 11:10:12,585 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C801A15690>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/f1aaf4c26ed28ffd8a940eb094f3acdc/execute/sync
2025-08-15 11:10:16,642 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C801995490>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/f1aaf4c26ed28ffd8a940eb094f3acdc/execute/sync
2025-08-15 11:10:20,697 - ERROR - Erreur majeure: HTTPConnectionPool(host='localhost', port=52692): Max retries exceeded with url: /session/f1aaf4c26ed28ffd8a940eb094f3acdc/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C801940B90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 493, in _make_request
    conn.request(
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 494, in request
    self.endheaders()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 325, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001C801940B90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 165, in scrape_google_maps
    scroll_to_load_results(driver, max_results)
  File "C:\wamp64\www\ScrappingNum-api\scrapping-back\gmaps.py", line 105, in scroll_to_load_results
    current_height = driver.execute_script("return arguments[0].scrollHeight;", container)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 555, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in execute
    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 406, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 430, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 459, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjaber\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52692): Max retries exceeded with url: /session/f1aaf4c26ed28ffd8a940eb094f3acdc/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C801940B90>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-08-15 11:10:24,761 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8019A1850>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/f1aaf4c26ed28ffd8a940eb094f3acdc
2025-08-15 11:10:28,812 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8019A9FD0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/f1aaf4c26ed28ffd8a940eb094f3acdc
2025-08-15 11:10:32,859 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C801A28090>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/f1aaf4c26ed28ffd8a940eb094f3acdc
2025-08-15 11:10:36,917 - INFO - --- Recherche pour mot-clé: orthodontiste ---
2025-08-15 11:10:45,260 - INFO - --- Recherche pour mot-clé: dentiste ---
2025-08-15 11:10:47,166 - INFO - Recherche: dentiste à Paris
2025-08-15 11:12:20,486 - INFO - --- Recherche pour mot-clé: cabinet dentaire ---
2025-08-15 11:12:22,149 - INFO - Recherche: cabinet dentaire à Paris
2025-08-15 11:26:31,135 - INFO - --- Recherche pour mot-clé: dentiste ---
2025-08-15 11:26:33,349 - INFO - Recherche: dentiste à Paris
2025-08-15 11:26:45,489 - INFO - 1/2: Clinique des Champs Elysées Paris 3ème Sébastopol - Médecine esthétique
2025-08-15 11:26:45,548 - INFO - Retour à la liste (mobile).
2025-08-15 11:26:49,958 - INFO - 2/2: Centre médical, dentaire et radiologique Jack Senet
2025-08-15 11:27:15,996 - INFO - --- Recherche pour mot-clé: Café ---
2025-08-15 11:27:17,696 - INFO - Recherche: Café à Paris
2025-08-15 11:27:27,226 - INFO - 1/2: Cafés Méo Saint Lazare
2025-08-15 11:27:27,296 - INFO - Retour à la liste (mobile).
2025-08-15 11:27:31,405 - INFO - 2/2: Terres de Café Paris Saint-Honoré
